name: Deploy Next.js App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Navigate to service-call-app directory
      working-directory: ./service-call-app
      run: npm install

    - name: Generate Prisma Client
      working-directory: ./service-call-app
      run: npx prisma generate

    - name: Build App
      working-directory: ./service-call-app
      run: npm run build

    - name: List .next Directory Contents for Verification
      working-directory: ./service-call-app
      run: ls -la .next
      

    - name: Set up SSH Key
      working-directory: ./service-call-app
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY_PEM }}" | tr -d '\r' > private_key.pem
        chmod 600 private_key.pem

    - name: Upload Built Files to Lightsail with rsync
      working-directory: ./service-call-app
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" .next/ ubuntu@${{ secrets.LIGHTSAIL_SERVER_IP }}:/home/ubuntu/ServiceCallDashboard/service-call-app/.next

    - name: Restart PM2 Using SSH
      working-directory: ./service-call-app
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.LIGHTSAIL_SERVER_IP }} << 'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Load nvm
          cd /home/ubuntu/ServiceCallDashboard/service-call-app
          npm install
          /home/ubuntu/.nvm/versions/node/v22.6.0/bin/pm2 restart service-call-app  # Restart the app using pm2
        EOF

    - name: Clean Up SSH Key
      working-directory: ./service-call-app
      run: rm private_key.pem
