name: Deploy Next.js App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Navigate to service-call-app directory
      working-directory: ./service-call-app
      run: npm install

    - name: Generate Prisma Client
      working-directory: ./service-call-app
      run: npx prisma generate

    - name: Build App
      working-directory: ./service-call-app
      run: npm run build

    - name: List .next Directory Contents for Verification
      working-directory: ./service-call-app
      run: ls -la .next
      

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY_PEM }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Upload Built Files to Lightsail with rsync
      working-directory: ./service-call-app
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" .next/ ubuntu@${{ secrets.LIGHTSAIL_SERVER_IP }}:/home/ubuntu/ServiceCallDashboard/service-call-app/.next

    - name: Upload Other Files (Optional)
      working-directory: ./service-call-app
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" package.json public/ ubuntu@${{ secrets.LIGHTSAIL_SERVER_IP }}:/home/ubuntu/ServiceCallDashboard/service-call-app/

    - name: Restart PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
        script: |
          cd /home/ubuntu/ServiceCallDashboard/service-call-app
          npm install
          pm2 restart service-call-app
