name: Deploy Next.js App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Navigate to service-call-app directory
      working-directory: ./service-call-app
      run: npm install

    - name: Generate Prisma Client
      working-directory: ./service-call-app
      run: npx prisma generate

    - name: Build App
      working-directory: ./service-call-app
      run: npm run build
      

    - name: Upload Built Files to Lightsail
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.LIGHTSAIL_SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
        source: ".next/*"
        target: "/home/ubuntu/ServiceCallDashboard/service-call-app/.next"

    - name: Upload Other Files (Optional)
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.LIGHTSAIL_SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
        source: |
          package.json
          public/*
        target: "/home/ubuntu/ServiceCallDashboard/service-call-app/"

    - name: Restart PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
        script: |
          cd /home/ubuntu/ServiceCallDashboard/service-call-app
          npm install
          pm2 restart service-call-app
